### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by nooryaseen428** [Web1-Teams/8am-grp6-repo#5]

**Comment by badrikh** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AN-Najah-hospital</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div id="feedback-page">
        <header>
          <h1>Feedback</h1>
        </header>
        <main>
          <section>
            <h2>Leave Your Feedback</h2>
            <form>
              <textarea placeholder="Write your feedback here..." rows="5" cols="30"></textarea>
              <br>
              <button type="submit">Submit Feedback</button>
            </form>
          </section>
        </main>
      </div>

    
</body>
</html>

**Comment by badrikh** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AN-Najah-hospital</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div id="feedback-page">
        <header>
          <h1>Feedback</h1>
        </header>
        <main>
          <section>
            <h2>Leave Your Feedback</h2>
            <form>
              <textarea placeholder="Write your feedback here..." rows="5" cols="30"></textarea>
              <br>
              <button type="submit">Submit Feedback</button>
            </form>
          </section>
        </main>
      </div>

    
</body>
</html>
