### ISSUE TITLE
the physical therapy department

### ISSUE THREAD

**Issue by nooryaseen428** [Web1-Teams/8am-grp6-repo#8]

**Comment by AmeedToqan** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
 

</head>

<body>
    <div>
        <h1>Physical therapy : </h1>
        <img src=".\Physical therapy.jpg" alt="">
<pre>
    Physical therapy is a common treatment that can help you recover after an injury or surgery,
     or manage symptoms from a health condition that affects how you move.
      It’s a combination of exercises, stretches and movements that’ll increase your strength,
       flexibility and mobility to help you move safely and more confidently.
    </pre>

    <h2>The Benefits of Physical Therapy :</h2>

    <ol>
        <li>Pain management.</li>
        <li>Avoiding surgery.</li>
        <li>Improved mobility and movement.</li>
        <li>Injury recovery or prevention.</li>
        <li>Recovery from stroke or paralysis.</li>
        <li>Fall prevention.</li>
        <li>Manage age-related medical issues.</li>

    </ol>

    </div>
</body>

</html>

**Comment by AmeedToqan** [comment]
> <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

</head>

<body>
    <div>
        <h1>Physical therapy : </h1>
        <img src=".\Physical therapy.jpg" alt="">
<pre>
    Physical therapy is a common treatment that can help you recover after an injury or surgery,
     or manage symptoms from a health condition that affects how you move.
      It’s a combination of exercises, stretches and movements that’ll increase your strength,
       flexibility and mobility to help you move safely and more confidently.
    </pre>

    <h2>The Benefits of Physical Therapy :</h2>

    <ol>
        <li>Pain management.</li>
        <li>Avoiding surgery.</li>
        <li>Improved mobility and movement.</li>
        <li>Injury recovery or prevention.</li>
        <li>Recovery from stroke or paralysis.</li>
        <li>Fall prevention.</li>
        <li>Manage age-related medical issues.</li>

    </ol>

    </div>
</body>

</html>

**Comment by AmeedToqan** [comment]
`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

</head>

<body>
    <div>
        <h1>Physical therapy : </h1>
        <img src=".\Physical therapy.jpg" alt="">
<pre>
    Physical therapy is a common treatment that can help you recover after an injury or surgery,
     or manage symptoms from a health condition that affects how you move.
      It’s a combination of exercises, stretches and movements that’ll increase your strength,
       flexibility and mobility to help you move safely and more confidently.
    </pre>

    <h2>The Benefits of Physical Therapy :</h2>

    <ol>
        <li>Pain management.</li>
        <li>Avoiding surgery.</li>
        <li>Improved mobility and movement.</li>
        <li>Injury recovery or prevention.</li>
        <li>Recovery from stroke or paralysis.</li>
        <li>Fall prevention.</li>
        <li>Manage age-related medical issues.</li>

    </ol>

    </div>
</body>

</html>`

**Comment by AmeedToqan** [comment]
``<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

</head>

<body>
    <div>
        <h1>Physical therapy : </h1>
        <img src=".\Physical therapy.jpg" alt="">
<pre>
    Physical therapy is a common treatment that can help you recover after an injury or surgery,
     or manage symptoms from a health condition that affects how you move.
      It’s a combination of exercises, stretches and movements that’ll increase your strength,
       flexibility and mobility to help you move safely and more confidently.
    </pre>

    <h2>The Benefits of Physical Therapy :</h2>

    <ol>
        <li>Pain management.</li>
        <li>Avoiding surgery.</li>
        <li>Improved mobility and movement.</li>
        <li>Injury recovery or prevention.</li>
        <li>Recovery from stroke or paralysis.</li>
        <li>Fall prevention.</li>
        <li>Manage age-related medical issues.</li>

    </ol>

    </div>
</body>

</html>``
